### ISSUE TITLE
Dataset copiado

### ISSUE THREAD

**Issue by evysb** [ICA-PUC/ml-task-manager#8]
O .csv era para ser copiado para a pasta tbm??

**Comment by humble-beaver** [comment]
Se não me engano nós partimos do pressuposto de que o .csv já existiria em um local padrão, por isso só referenciamos o seu nome.

**Comment by evysb** [comment]
É pq ficaríamos dependendo do BA, mas acho que não vamos conseguir usar ele agora. Vou ver com o Cris qual melhor forma da gente deixar isso por enquanto
